baseurl = "https://gaultierq.github.io/qaunt2"
languageCode = "en-us"
title = "Quentin Gaultier"
theme = "hugo-freelancer-theme"



[params]

    # You can use Markdown syntax for urls [text](//url.to/source) for
    # most longer texts.

    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "QG"
    description = "Welcome"
    email = "your@email.com"

    # Custom assets
	custom_css = []
	custom_js  = []

    [params.navigation]
        brand = "QG"


    [params.header]
        # Copy your own image into './static/img/'' if you wish
        image = "profile.png"
        name = "QG"
        subtitle = "Nomad Programmer"


    [params.portfolio]
        # All projects defined in their own files. You can find example projects
        # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
        # at the root of this Hugo site.
        # For more informtion take a look at the README.
        title = "Portfolio"

        [params.portfolio.modal]
            client = "Client"
            date = "Date"
            category = "Category"
            buttontext = "Close"


    [params.about]
        title = "About"
        # The about text is splitted into a left and right column
        left = "Hi,  my name is Quentin Gaultier, I'm a software engineer. \n\nOriginally from Paris, I am currently enjoying a nomadic lifestyle."
        right = "- java ++++ \n- android ++++\n- sh ++\n- html ++\n- js ++\n- typescript ++\n- linux +"

        [params.about.button]
            text = "Download theme"
            link = "/about"
            icon = "download"


    [params.contact]
        title = "Contact"

        
        [params.contact.form.name]
            text = "Name"
            error = "Please enter your name."

        [params.contact.form.email]
            text = "Email Address"
            error = "Please enter your email address."

        [params.contact.form.phone]
            text = "Phone Number"
            error = "Please enter your phone number."

        [params.contact.form.message]
            text = "Message"
            error = "Please enter a message."

        [params.contact.form.button]
            text = "Send"


    [params.footer]
        copyright = "Published under the Apache License 2.0. Powered by [Hugo](//gohugo.io)."

        [params.footer.location]
            title = "Location"
            # Postal address (add as many lines as necessary)
            address = ["Undefined"]

        [params.footer.social]
            title = "Around the web"
            # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
            # for more icons. The icons are represented by their corresponding
            # CSS class.
            [[params.footer.social.networks]]
                icon = "fa-github"
                link = "//github.com/gaultierq"

            [[params.footer.social.networks]]
                icon = "fa-stack-overflow"
                link=  "//stackoverflow.com/users/1929671/quentin-gaultier"

            [[params.footer.social.networks]]
                icon = "fa-twitter"
                link=  "//twitter.com/gaultierq"


        [params.footer.credits]
            title = "About Freelancer"
            text = "Freelance is a free to use, open source Bootstrap theme created by [Start Bootstrap](startbootstrap.com)."
